### ISSUE TITLE
Creating Tabs / fil them? :)

### ISSUE THREAD

**Issue by enaske** [kaminaris/StdUi#2]
Hey guys,

So I try to create Tabs with your GUI, not sure if they completly in yet.
I am curious, how I fil the Tabs with Content or how I can redesign the Buttons? Also if I do a 4 Tab Menu, the 4th Button seems not to work.

Also I am curious if there is a way to make "General Settings" Global and 2/3/4 Settings class Specific? :)

Hope you guys can Show me a example :) Thanks

My example Code is:

local function TestMenu()

    local tabs = {
 {
     name = 'firstTab',
     title = 'General Settings',
    
 },
{
     name = 'secondTab',
    title = TEstSettings',
},
 {
    name = 'thirdTab',
    title = Test Settings'
},
{
    name = 'thirdTab',
    title = Test Settings'
}
}
    local window = StdUi:TabPanel(UIParent, 700, 500, tabs, vertical)
    window:SetPoint('CENTER');

end

**Comment by pwilkowski** [comment]
I just updated docs with demo for Tab container
https://github.com/kaminaris/StdUi/wiki/Tab-Container

**Comment by AmsTaFFix** [comment]
@pwilkowski hi, can we close that issue? As I see it has been solved already
