### ISSUE TITLE
Haunted borders

### ISSUE THREAD

**Issue by OperatorMaeJong** [kaminaris/StdUi#23]
Just borders randomly becoming bold on random edges. It's that one good old bug.

![WowClassic_DCiChqGW17](https://user-images.githubusercontent.com/96477212/146927065-6dde4bba-7744-4a7d-bbae-e14e5d8b8ce0.jpg)

My UI scale is set to 1.0. Other than that, I have no clue on other possible ways to reproduce this. I figured it might just be caused by some scaling rounding errors or likewise.

**Comment by pwilkowski** [comment]
UI Scale is the issue, 1.0 doesnt mean pixel perfection, see how ElvUI is managing UI scale to make itself pixel perfect

**Comment by OperatorMaeJong** [comment]
Yeah, I just assumed 1.0 meant there wasn't any rounding done behind the curtains
