### ISSUE TITLE
PanelWithTitle

### ISSUE THREAD

**Issue by doadin** [kaminaris/StdUi#25]
Hello, I am probabbly doing something wrong but I am trying to use the below code.

```
local LibStub = _G.LibStub

local StdUi = LibStub("StdUi")

local MainFrame = StdUi:Window(UIParent, 750, 500, 'Test Window')
MainFrame:SetPoint('CENTER')
MainFrame:Show()

local columnHeaders = {
    {
        name = 'Name',
        width = 50,
        align = 'LEFT',
        defaultsort = 'dsc',
        sortnext = 3,
        index = 'name',
        format = 'string',
    },
    {
        name = 'Level',
        width = 60,
        align = 'RIGHT',
        defaultsort = 'dsc',
        index = 'level',
        format = 'string',
    },
    {
        name = 'Average Item Level',
        width = 120,
        align = 'RIGHT',
        defaultsort = 'dsc',
        index = 'avgItemLevel',
        format = 'string',
    },
}

local PlayerHeading = StdUi:PanelWithTitle(MainFrame, 750, 250, "Player's Keys", 25, 16)
StdUi:GlueTop(PlayerHeading, MainFrame, 0, -100)

local st = StdUi:ScrollTable(PlayerHeading, columnHeaders)
StdUi:GlueTop(st, PlayerHeading, 0, -50)

local GuildcolumnHeaders = {
    {
        name = 'Name',
        width = 100,
        align = 'LEFT',
        defaultsort = 'dsc',
        sortnext = 3,
        index = 'name',
    },
    {
        name = 'Level',
        width = 80,
        align = 'RIGHT',
        defaultsort = 'dsc',
        index = 'Level',
    },
}

local GuildHeading = StdUi:PanelWithTitle(MainFrame, 750, 250, "Guild Member's Keys", 25, 16)
StdUi:GlueTop(GuildHeading, MainFrame, 0, -400)

local Guildst = StdUi:ScrollTable(GuildHeading, GuildcolumnHeaders)
StdUi:GlueTop(Guildst, GuildHeading, 0, -50)

st:SetData({})
Guildst:SetData({})
```

GuildHeading  refuses to grow no matter what value I put in.
local GuildHeading = StdUi:PanelWithTitle(MainFrame, 750, 250, "Guild Member's Keys", 25, 16)
same as
local GuildHeading = StdUi:PanelWithTitle(MainFrame, 750, 2500, "Guild Member's Keys", 25, 16)
Or any number inbetween. The MainFrame however does grow.

**Comment by pwilkowski** [comment]
Panel with title is extremely simple code:

```lua
function StdUi:PanelWithTitle(parent, width, height, text)
	local frame = self:Panel(parent, width, height);

	frame.titlePanel = self:PanelWithLabel(frame, 100, 20, nil, text);
	frame.titlePanel:SetPoint('TOP', 0, -10);
	frame.titlePanel:SetPoint('LEFT', 30, 0);
	frame.titlePanel:SetPoint('RIGHT', -30, 0);
	frame.titlePanel:SetBackdrop(nil);

	return frame;
end
```

Try to isolate your code and see which part breaks it.

also use `/tinspect` to investigate which frame exactly does not grow

**Comment by doadin** [comment]
@pwilkowski 
so it appears that even though setting the height in:
local GuildHeading = StdUi:PanelWithTitle(MainFrame, 750, 250, "Guild Member's Keys", 25, 16)

larger will increase the size of MainFrame it still is not like considered as fitting, if I change:
local MainFrame = StdUi:Window(UIParent, 750, 500, 'Test Window')
to
local MainFrame = StdUi:Window(UIParent, 750, 700, 'Test Window') 

GuildHeading will then grow. Little confusing.

**Comment by doadin** [comment]
@pwilkowski Also StdUi:PanelWithTitle according to wiki is StdUi:PanelWithTitle(parent, width, height, text, titleWidth, titleHeight) is titleWidth, titleHeight not supprted anymore?

**Comment by pwilkowski** [comment]
As far as I remember that is how default frames behaves. Wouldn't bet my arm on it. There is a lot of confusing things with wow ui code.

And yes, titleWidth, titleHeight is not supprted anymore. You can access title panel with `frame.titlePanel`

**Comment by doadin** [comment]
@pwilkowski Thanks for the info, I am trying to convert from ace to stdui due to some issues stdui seems to deal better with. I am having an issue with one of my scrolltable data tables, however unless im overlooking something its created the same way as the other data tables that work, just different data inserted. I am getting a lua error from SortData being nil I if I remember right is there a way to like verify data table format easily? With the same code if I copy the code to generate the data table from the wiki here SetData() works but if I give it my generated table it stops working so its seeming got to be a table format issue but looking at the table data it looks to me to be correct.

**Comment by pwilkowski** [comment]
You can check AuctionFaster addon for hints how i used it.
