### ISSUE TITLE
Dragonflight Bug: SetFont() in SimpleEditBoxMethods has Invalid Syntax

### ISSUE THREAD

**Issue by Xatan** [kaminaris/StdUi#28]
Line 19 of EditBox.lua
	self:SetFont(self:GetFont(), newSize, self.stdUi.config.font.effect);
causes a lua error that the SetFont() call is invalid syntax.
Maybe 'NONE' is an invalid font effect or some of the other arguments  are invalid or the syntax has changed?

Please fix this urgently so that all addons using the StdUi library will have the fix installed, to prevent breaking other addons using StdUi.
This can be tested in the Dragonflight Beta or PTR now.

**Comment by Xatan** [comment]
https://wowpedia.fandom.com/wiki/Patch_10.0.0/API_changes

Widget APIs now strictly validate supplied parameters, erroring if invalid values are supplied.
Region creation functions such as [Frame:CreateTexture](https://wowpedia.fandom.com/wiki/API_Frame_CreateTexture)() and [Frame:CreateFontString](https://wowpedia.fandom.com/wiki/API_Frame_CreateFontString)() will error if supplied invalid draw layer names.
Functions such as [Region:GetPoint](https://wowpedia.fandom.com/wiki/API_Region_GetPoint)() and [FontInstance:SetFont](https://wowpedia.fandom.com/wiki/API_FontInstance_SetFont)() will error in cases where nil values are supplied in-place of expected parameters.

**Comment by Xatan** [comment]
This can be easily fixed by ensuring that there are no nil arguments to SetFont().
So if the 3rd argument for SetFont() is not defined then simply make the 3rd argument a zero length string "".
'NONE' is an invalid argument value for a Font Effect, so if 'NONE' is specified in the self.stdUI.config.font.effect value then make the 3rd argument a non-nil string "" also.

**Comment by pwilkowski** [comment]
If you make the pull request i can merge it, however i no longer play the game so can't even test it
