### ISSUE TITLE
Allow valueStep to be set on Slider creation

### ISSUE THREAD

**Issue by Wutname1** [kaminaris/StdUi#3]
Simple addition to allow the valueStep to be set on the slider. 

Example:
`StdUi:Slider(parent, width, height, value, vertical, min, max)`
to
`StdUi:Slider(parent, width, height, value, vertical, min, max, step)`

**Comment by pwilkowski** [comment]
sure but then you would have 8 arguments and that is a bit too much.
You can always set step later:
```lua
slider:SetValueStep(value)```

**Comment by Wutname1** [comment]
Ya, just a suggestion since step tends to be set often.
