### ISSUE TITLE
Persistance?

### ISSUE THREAD

**Issue by veldt1** [kaminaris/StdUi#39]
Using this without LibStub - I've got it loaded in my addon and everything works, except nothing seems to be persistent - when a user reloads, all the settings they had selected are reset.

How would you recommend setting up persistence? Would have posted this as a question but there do not seem to be any labels.

**Comment by pwilkowski** [comment]
You need to implement persistance yourself, stdui doesn't touch on that.

**Comment by veldt1** [comment]
> You need to implement persistance yourself, stdui doesn't touch on that.

I've been working on a fork with persistence. I'm going to be using it for myself, would you be interested in me opening a pull request when it's done, or do you have no interest in supporting persistence?
